spring:
  data:
    mongodb:
      port: 0
      database: maindb

  shell:
    interactive:
      enabled: true
    command:
      version:
        enabled: false
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2